LIBNAME mydata "~/Mydata/";

DATA myexample;
	SET mydata.wound;
RUN;


PROC FORMAT;
	VALUE FMTWOUND 0="NONPENETRATE" 1="PENETRATE";
RUN;

ODS GRAPHICS OFF;

TITLE "HISTOGRAMS of SBP by GENDER and WOUND TYPE";

PROC UNIVARIATE DATA=Mydata.WOUND NOPRINT;
	/*Type the code to add class for histograms here*/
	CLASS GENDER WOUND;
	VAR SBP;
	HISTOGRAM / NROWS=2 NCOLS=2 CFILL=RED PFILL=M3N45;
	INSET N='N:' (4.0) MIN='MIN:' (4.1) MAX='MAX:' (4.1) / NOFRAME POSITION=NE;
	FORMAT WOUND FMTWOUND.;
RUN;